name: housing-price-feature-monthly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 23 * *'
permissions:
  contents: write

jobs:
  update-csv :
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install pandas schedule requests

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run 'fetch-data-monthly'
      run: python Final_Project/src/fetch-data-monthly.py

    - name: Commit new registry
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "Monthly automatic update of the registry" --allow-empty)
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 

    - name: Run 'feature_engineering_pipeline'
      run: python Final_Project/src/feature_engineering_pipeline.py

    - name: Commit clean registry
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "Monthly automatic update of the registry" --allow-empty)

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 